### ISSUE TITLE
Underscore in slug causes 500 ISE

### ISSUE THREAD

**Issue by Kelketek** [concentricsky/badgr-server#1]
If one tries to create a badge with a slug that has an underscore in it, the server throws a 500 instead of a 400. Underscores are valid characters in Django slugs, so the URL pattern probably just needs to be updated to allow this.

    Internal Server Error: /v1/issuer/issuers/test-issuer/badges
    Traceback (most recent call last):
      File "/home/badges/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/badges/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
        return view_func(*args, **kwargs)
      File "/home/badges/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
        return self.dispatch(request, *args, **kwargs)
      File "/home/badges/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
        response = self.handle_exception(exc)
      File "/home/badges/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
        response = handler(request, *args, **kwargs)
      File "/home/badges/badgr-server/apps/issuer/api.py", line 340, in post
        description=request.data.get('description')
      File "/home/badges/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 165, in save
        self.instance = self.create(validated_data)
      File "/home/badges/badgr-server/apps/issuer/serializers.py", line 130, in create
        full_url = new_badgeclass.get_full_url()
      File "/home/badges/badgr-server/apps/issuer/models.py", line 38, in get_full_url
        return settings.HTTP_ORIGIN + self.get_absolute_url()
      File "/home/badges/badgr-server/apps/issuer/models.py", line 96, in get_absolute_url
        return reverse('badgeclass_json', kwargs={'slug': self.slug})
      File "/home/badges/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
        return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
      File "/home/badges/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
        (lookup_view_s, args, kwargs, len(patterns), patterns))
    NoReverseMatch: Reverse for 'badgeclass_json' with arguments '()' and keyword arguments '{'slug': u'edxdemoxdemo_course'}' not found. 1 pattern(s) tried: ['public/badges/(?P<slug>[\\-0-9a-z]+)$']
    [30/Apr/2015 11:42:19] "POST /v1/issuer/issuers/test-issuer/badges HTTP/1.1" 500 118284

**Comment by ottonomy** [comment]
Thanks for the report. You were absolutely right that updating the Regex in the urlconfig would be the solution. It's now fixed and tested on the develop branch and will be pulled into the next release. See 1b048f37e395c2550398beb036106785a67655c0 .
