### ISSUE TITLE
TypeError when setting up db and options line is uncommented

### ISSUE THREAD

**Issue by alexlittle** [concentricsky/badgr-server#164]
## System information & context:
- Operating system you are using: Ubuntu 18.04, python 2.7, mysql
- Browser & version: n/a - on command line
- URL or path of the screen where you encountered this issue or would like to see a new feature: n/a on command line

## Description of issue or feature request, including any error messages:

After editing the setting_local.py (the db name/user etc), I also uncommented the options line (as recommended in the comment "Uncomment when using MySQL to ensure consistency across servers").
However, with the options uncommented and then running the ./manage.py migrate command, I got a TypeError (see stacktrace below). When I re-commented the line, the migration ran fine.

Please let me know if you need any extra info about the versions etc I'm using.

---
Stack trace:
 ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 61, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 188, in connect
    conn_params = self.get_connection_params()
  File "/home/alex/data/Digital-Campus/development/core/badgr/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 256, in get_connection_params
    isolation_level = options.pop('isolation_level', None)
TypeError: pop() takes no arguments (2 given)

**Comment by 24akhil** [comment]
I am also facing the same issue while trying to run in production server with docker-compose. Is there any work around for this.
