### ISSUE TITLE
ImportError: cannot import name TemplateDoesNotExist

### ISSUE THREAD

**Issue by jasonhemu** [concentricsky/badgr-server#29]
Hi all,

I am stuck at "./manage.py migrate" step. 

`File "/usr/local/lib/python2.7/dist-packages/jingo/__init__.py", line 11, in <module> from django.template.base import Origin, TemplateDoesNotExist 
ImportError: cannot import name TemplateDoesNotExist`

Does anyone know how to solve this import error? Thanks much in advance!

Best,
Mu

**Comment by ottonomy** [comment]
Hi, @jasonhemu: What operating system are you using? Did you create a virtualenv, and did you activate it? Did you encounter any issues while running `pip install -r requirements-dev.txt`?

Thanks!

**Comment by teopost** [comment]
I have the same error. 
I use Centos 7.0

```
(env)[root@localhost code]# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/root/badgr/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/root/badgr/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/root/badgr/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/badgr/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/root/badgr/env/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/badgr/env/lib/python2.7/site-packages/jingo/__init__.py", line 11, in <module>
    from django.template.base import Origin, TemplateDoesNotExist
ImportError: cannot import name TemplateDoesNotExist
(env)[root@localhost code]# 
```

**Comment by ottonomy** [comment]
jingo has now been removed from the package and should no longer affect users attempting to run migrations.
