### ISSUE TITLE
Badgr server crashing after installation

### ISSUE THREAD

**Issue by s4trace** [concentricsky/badgr-server#42]
## System information: 
- Operating system you are using: Ubuntu 16.04
- Browser & version: Firefox 
- URL of the page where you encountered this issue: http://localhost:8000/accounts/login
- If your issue refers to the Badgr app in the Canvas LMS, the url of your canvas server or course where the problem occurred.
    - Course URL: 

## Description of issue, including any error messages:
 We are trying to run the openbadges server locally and we just finished the instructions on creating a local development environment. However, whne we try to access the local url, the server crashes and we receive the following error: 

ImportError: No module named django_auth_lti.middleware

We've tried to fix the issue ourselves but we weren't capable of fixing it. These are the error messages we get when the server starts crashing:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_auth_lti.middleware
[16/Nov/2016 08:11:21] "GET /accounts/login HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_auth_lti.middleware
[16/Nov/2016 08:11:22] "GET /favicon.ico HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/torasu/badgr/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_auth_lti.middleware
[16/Nov/2016 08:11:22] "GET /favicon.ico HTTP/1.1" 500 59`

**Comment by ottonomy** [comment]
Looks like you couldn't successfully install a package from the requirements. 

You may solve this issue by removing the LTI middleware from your middleware settings. 

in apps/mainsite/settings_local.py, overwrite the middleware classes declaration to take out the problem class.

```py
MIDDLEWARE_CLASSES = [
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django_auth_lti.middleware.LTIAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mainsite.middleware.MaintenanceMiddleware',
    'badgeuser.middleware.InactiveUserMiddleware',
]
```

**Comment by ottonomy** [comment]
The LTIAuthMiddleware is no longer included in the settings file. Thanks!
