### ISSUE TITLE
DoesNotExist: BadgrApp matching query does not exist.

### ISSUE THREAD

**Issue by miekassu** [concentricsky/badgr-server#65]
Hi,

I cloned server and UI repos. Followed installation guide and got everything running like I assumed.
But now, whenever I try to post something thru UI, I will get:

> DoesNotExist: BadgrApp matching query does not exist.

Localhost:8000/staff is working as I assume.

Ideas?

Full terminal code, when tried to Create Badgr Account: 
`
Internal Server Error: /v1/user/profile
Traceback (most recent call last):
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kasperhamalainen/badgr/code/apps/badgeuser/api.py", line 57, in post
    new_user = serializer.save()
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/Users/kasperhamalainen/badgr/code/apps/badgeuser/serializers_v1.py", line 52, in create
    request=self.context.get('request', None),
  File "/Users/kasperhamalainen/badgr/code/apps/badgeuser/managers.py", line 43, in create
    badgrapp = BadgrApp.objects.get_current(request=request)
  File "/Users/kasperhamalainen/badgr/code/apps/mainsite/models.py", line 94, in get_current
    return self.get(id=badgr_app_id)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/kasperhamalainen/badgr/env/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: BadgrApp matching query does not exist.
[18/May/2018 09:29:38] "POST /v1/user/profile HTTP/1.1" 500 22476
`

Thanks!

**Comment by ottonomy** [comment]
@miekassu Looks like you need to create a BadgrApp record. You'll need at least one for Badgr-server to operate properly.

I have added instructions to the readme in 8875790. Thanks!

**Comment by matty111** [comment]
I have now the same problem. I created only the superuser and in your readme i don't find the solution
